### ISSUE TITLE
Apply colors in HTML/CSS not in JS

### ISSUE THREAD

**Issue by adelnizamutdinov** [ChanceArthur/tailwindcss-dark-mode#14]
Is it possible to do this https://github.com/ChanceArthur/tailwindcss-dark-mode/blob/master/prefers-dark.js but in HTML/CSS ? The screen flickers when the color is applied in JS (1 frame is rendered in light, and then dark is applied)

**Comment by ChanceArthur** [comment]
You can try something like [this](https://github.com/ChanceArthur/tailwindcss-dark-mode/issues/4#issuecomment-540552875), but I haven't tested it.

Actual CSS would be something like...
```
@media screen and (prefers-color-scheme: dark) {
 .element {
    background-color: #000;
    color: #fff;
  }
}
```

**Comment by adelnizamutdinov** [comment]
it works! Thank you so much!
