### ISSUE TITLE
Placeholder don't seem working with dark variant

### ISSUE THREAD

**Issue by Bricklou** [ChanceArthur/tailwindcss-dark-mode#17]
When I try to do `dark:placeholder-gray-300` on an input field, it doesn't change the color of my placeholder. It seem that a `::placeholder` pseudo class is missing:

![image](https://user-images.githubusercontent.com/15181236/79686165-93f34b80-823e-11ea-960d-94daabc5b3b6.png)

**Comment by ChanceArthur** [comment]
That variant is not currently included. Refer to the README for supported variants.

**Comment by Bricklou** [comment]
I already done some configuration in my `tailwind.config.js` but it change nothing.

There is my configuration:
```js
module.exports = {
  theme: {
    extend: {},
    darkSelector: '.dark-mode',
  },
  variants: {
    backgroundColor: [
      'dark',
      'dark-hover',
      'dark-group-hover',
      'dark-even',
      'dark-odd',
      'hover',
    ],
    borderColor: ['dark', 'dark-focus', 'dark-focus-within', 'hover'],
    textColor: ['dark', 'dark-hover', 'dark-active', 'hover'],
    placeholderColor: ['dark', 'dark-hover', 'dark-active', 'hover'],
  },
  plugins: [require('tailwindcss-dark-mode')()],
}
```

**Comment by ChanceArthur** [comment]
I've just published an update that adds support for the placeholder pseudo-selector. Run an update and remember to add it into your config. Let me know if it works for you.

**Comment by Bricklou** [comment]
Yes, it's working now.
![image](https://user-images.githubusercontent.com/15181236/79890666-1f680a80-8400-11ea-9725-c0fe7e98a378.png)

Thanks
