### ISSUE TITLE
:hover doesn't work in light mode when installed

### ISSUE THREAD

**Issue by mc4rdle** [ChanceArthur/tailwindcss-dark-mode#18]

**Comment by ChanceArthur** [comment]
Can you provide more detail? What does your config look like?

**Comment by mc4rdle** [comment]
Here is my tailwind config file, I'm using Laravel Mix also. Hover and transition classes work when removing dark mode from the config file.

module.exports = {
    important: true,
    theme: {
        fontFamily: {
            body: ['Inter', 'sans-serif'],
        }
    },
    variants: {
        opacity: ["responsive", "hover"],
        backgroundColor: ['dark', 'dark-hover', 'dark-group-hover', 'dark-even', 'dark-odd'],
        borderColor: ['dark', 'dark-focus', 'dark-focus-within'],
        textColor: ['dark', 'dark-hover', 'dark-active', 'dark-placeholder']
    },
    plugins: [
        require("@tailwindcss/ui"),
        require("tailwindcss-dark-mode")()
    ]
};

**Comment by ChanceArthur** [comment]
You need to specify "hover" as well as "dark-hover" on those utilities. Former is for light/default, latter is for dark. Try that.

**Comment by mc4rdle** [comment]
Worked! Thanks alot.
