### ISSUE TITLE
.dark\:text-white cannot be found

### ISSUE THREAD

**Issue by CasperEngl** [ChanceArthur/tailwindcss-dark-mode#2]
First of all, very nice plugin idea for a plugin. I have this issue if I try to use dark variants in my `style.scss` with `@apply`. Otherwise, it works like a charm in normal class names.

```
Syntax error: `@apply` cannot be used with `.dark\:text-white` because `.dark\:text-white` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.dark\:text-white` exists, make sure that any
 `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree. 
```

Do you know how to get around this?

**Comment by ChanceArthur** [comment]
`@apply` doesn't work with colons. You'll also get this error with the default variants, [as noted here](https://tailwindcss.com/docs/extracting-components/#extracting-css-components-with-apply). What you'll need to do instead is:

```css
.mode-dark .your-class {
  @apply text-white;
}

**Comment by CasperEngl** [comment]
Thanks for the clarification, and the quick response!

I've come up with a solution that works very well for me, to keep semantics with Tailwind, using the `@variants` directive.

```
.menu__link {
  @variants dark {
    @apply text-white;
  }
}
```

That way, I can just add `dark:menu__link` to my class list.

Perhaps it might be good to add in your README?

**Comment by ChanceArthur** [comment]
Very nice!

Yes, I'll update the README as I'm sure others will run into this.
