### ISSUE TITLE
Unable to use variants in @apply directive

### ISSUE THREAD

**Issue by ccapndave** [ChanceArthur/tailwindcss-dark-mode#22]
First of all, apologies if I am doing something wrong, but I can't figure out how to abstract out dark mode pseudo-selectors into `@apply`.

```
.form-text-input {
  @apply w-full inline-block appearance-none py-4 px-4 leading-tight text-gray-700 bg-gray-200 border border-gray-200 rounded;
}
.form-text-input:focus {
  @apply bg-white border-gray-500 outline-none;
}
.form-text-input:dark {
  @apply text-gray-200 bg-gray-700;
}
```

All of these work apart from the `dark` directive.  Any clues would be appreciated.

**Comment by ChanceArthur** [comment]
There is no "dark" pseudo-selector. You need prepend the selector for dark mode, which is `.mode-dark` by default.

```
.mode-dark .form-text-input {
  ...
}

.mode-dark .form-text-input:focus {
  ...
}
```

**Comment by ccapndave** [comment]
Of course :)

Thanks!
