### ISSUE TITLE
bg-opacity doesn't work

### ISSUE THREAD

**Issue by kinkwilde** [ChanceArthur/tailwindcss-dark-mode#27]
When using bg-opacity with dark properties it doesn't work.

`bg-gray-500 bg-opacity-75 opacity-0 hover:opacity-100`

but doing something like this doesn't work

`bg-gray-500 bg-opacity-75 opacity-0 hover:opacity-100 dark:bg-gray-800 dark:bg-opacity-50`

There doesn't appear to be anything anywhere in this plugin which will add in a new css variable above the previously defined variable for the dark property of the bg-opacity.

**Comment by ChanceArthur** [comment]
Did you [enable the variants](https://github.com/ChanceArthur/tailwindcss-dark-mode#enabling-variants) for the background and opacity utilities?

**Comment by kinkwilde** [comment]
Ah yes my mistake - thanks
