### ISSUE TITLE
Should this plugin be required?

### ISSUE THREAD

**Issue by l2zeo** [ChanceArthur/tailwindcss-dark-mode#28]
`
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      screens: {
        'dark': {'raw': '(prefers-color-scheme: dark)'},
        // => @media (prefers-color-scheme: dark) { ... }
      }
    }
  }
}
`

Should "dark mode screen" be required as above?
How do I handle CSS after applying the plugin?

**Comment by l2zeo** [comment]
As you can see, the whitelist is not applied.

**Comment by ChanceArthur** [comment]
Didn't see this because you closed it.
No. That's just an alternative method of dark mode without this plugin.

Enable this plugin and add the variants you need according to the README.
