### ISSUE TITLE
Feature: At Rule for Dark mode

### ISSUE THREAD

**Issue by blackfyre** [ChanceArthur/tailwindcss-dark-mode#3]
Great little tool! We really like at and decided to adopt it immediately! 😄 
But.... 😉 
As a developer who creates self-contained components with the corresponding postcss parts included into the component, a `@dark` `at-rule` would be beneficial.
This way, we can extract the de component css definitions into classes for both the light & dark theme and would result in a much cleaner code.

**Comment by m5o** [comment]
look at: https://stefanzweifel.io/posts/support-mojave-dark-mode-with-tailwind-css/

**Comment by blackfyre** [comment]
@m5o Definitely interesting, but with less than 5% browser adoption atm, it's more of an exotic thing than a solution.
https://caniuse.com/#feat=prefers-color-scheme

Wider adoption would be a great thing to have!

**Comment by Akryum** [comment]
It seems widely supported now :smile_cat:

**Comment by hawezo** [comment]
It's supported by all major browsers, except IE11 (if we can call that a major browser). 

https://caniuse.com/#search=prefers-color-scheme

**Comment by brandonpittman** [comment]
I created a plugin that adds actual Tailwind variants for light and dark based on media queries. 

https://github.com/brandonpittman/tailwindcss-plugin-design

**Comment by ChanceArthur** [comment]
I'd closed a related issue a while ago when this was solved. I guess I can close this one, too. We've currently got theme-based media queries via JS. I'm still considering implementing them in the plugin itself in the next major release.
