### ISSUE TITLE
"dark-disabled" doesn't appear to be a variant

### ISSUE THREAD

**Issue by gianniskarmas** [ChanceArthur/tailwindcss-dark-mode#32]
Hi and thank you for this plugin.
I'm on latest vite and tailwind + ui with vue3.
If I enable the variants like so:
```
  variants: {
    backgroundColor: ['dark', 'dark-hover', 'dark-group-hover', 'dark-even', 'dark-odd'],
    borderColor: ['dark', 'dark-disabled', 'dark-focus', 'dark-focus-within'],
    textColor: ['dark', 'dark-hover', 'dark-active', 'dark-placeholder'],
```
I get:
`Error: Your config mentions the "dark-disabled" variant, but "dark-disabled" doesn't appear to be a variant. Did you forget or misconfigure a plugin that supplies that variant?`

**Comment by ChanceArthur** [comment]
I guess I should've released it after adding it to the README. 🙃
Update and try again.
