### ISSUE TITLE
Style html tag

### ISSUE THREAD

**Issue by subhero24** [ChanceArthur/tailwindcss-dark-mode#35]
Adding a tailwind class to the html tag itself does not work as expected. The styles are not applied because the selectors look like `.dark-mode .bg-blue-500` (with a space between the classname selectors). If the generated selector was `.dark-mode.bg-blue-500, .dark-mode .bg-blue-500` it would work correctly.

Is this something that should be fixed? Can do a PR if you want?

**Comment by ChanceArthur** [comment]
Sorry for the wait. Yes, if that's something you need and you have a PR for it, I'll be happy to merge it for you.
