### ISSUE TITLE
Add support for prefers-color-scheme

### ISSUE THREAD

**Issue by ChanceArthur** [ChanceArthur/tailwindcss-dark-mode#4]
With iOS supporting dark mode soon, I think it might be a good idea to add support for prefers-color-scheme as an alternative to the current class method.

Likely with a `prefers-dark` variant. Open to thoughts and suggestions.

**Comment by dillingham** [comment]
related https://developer.apple.com/videos/play/wwdc2019/511/

**Comment by m5o** [comment]
Fyi, easy debugging on Safari Technology Preview and WebKit

> **Debugging Dark Mode**
Web Inspector now includes a navigation bar button in the Elements tab to toggle dark or light mode, depending on your current overall system preference. This allows you to quickly test pages in both appearances without having to toggle the whole system appearance in System Preferences. The Styles sidebar updates to reflect the current matching rules, as well as any CSS color variables.

https://webkit.org/blog/8840/dark-mode-support-in-webkit/

**Comment by blackfyre** [comment]
Currently, there's limited support for the required media query, and it's in an unofficial draft state. 
I'd recommend waiting a bit more first...

**Comment by nathanheffley** [comment]
While `prefers-color-scheme` isn't official, most browsers are implementing it and I find it unlikely that it's going to change. I would love to see a new major version released for this package with `dark:` as a variant using the media query instead of the class it currently uses. Developers who want to continue using the class could continue using the current version.

Within the next major version of any significant browser it will be supported, and this is a good example of progressive enhancement. Nothing will break if a user's browser doesn't support the new media query.

**Comment by ChanceArthur** [comment]
That was the idea. Both methods would be available. It's up to you which method to use.

I'm not sure when I can get around to it, but it's something I want to implement for sure.

**Comment by ghalex** [comment]
@nathanheffley this is already supported in tailwind:

```js
// tailwind.config.js
screens: {
  ...
  'dark': {'raw': '(prefers-color-scheme: dark)'},
},
```

and then you can use:

```html
<body class="bg-white dark:bg-black">
    ...
</body>
```

**Comment by ChanceArthur** [comment]
@ghalex Does this work in combination with other media queries, though?

**Comment by nathanheffley** [comment]
@ChanceArthur it does work pretty well (I use that method on my personal site) and it combines with `hover`, `focus`, etc. but having it be a screen doesn't allow for it to work in every situation.

Also it does not give an easy way to allow the user to toggle the theme as it is completely dependent on the OS settings. A package that could provide a single `dark` prefix that obeys OS settings unless overridden would be ideal.

**Comment by ghalex** [comment]
@ChanceArthur @nathanheffley  a simple code like this will work with `prefers-color-scheme` and with the extension too.

```js
function checkDarkMode() {
  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    return true
  }
  
  return false
}

if (checkDarkMode()) {
  document.documentElement.classList.add('dark-mode')
} else {
  document.documentElement.classList.remove('dark-mode')
}
```

will work with this extension pretty well.

**Comment by kabalage** [comment]
I prefer @ghalex's solution. This allows user overriding.

**Comment by ChanceArthur** [comment]
@ghalex's solution has replaced the time-based script in v1.1.1. Credited you in the release. :)

**Comment by ghalex** [comment]
Thank you @ChanceArthur.
